terrform creation

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -57,9 +57,9 @@ jobs:
         run: terraform plan -no-color -input=false -out=planfile
         continue-on-error: true
 
-      - name: Check Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # - name: Check Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
 
       - name: terraform apply
         id: apply
